#server:
#  port: 7077
#
#
#
#spring:
#  profiles:
#    active: prod
#---   # "---" 三个横线代表  一个yml 配置块    相当于一个新的文件
#server:
#     port: 9999
#
#spring:
#  profiles: dev
#
#
#---
#server:
#  port: 8888
#
#spring:
#  profiles: prod